services:
  backend:
      build: ./server
      container_name: backend
      restart: always
      ports: 
        - "3001:3001"
  frontend:
      build: ./client
      args:
        VITE_API_URL: http://16.170.246.235/api
      container_name: frontend
      restart: always
      ports: 
        - "5173:5173"    
      depends_on: 
        - backend
