const path = require('node:path')

console.log(__filename)
console.log(__dirname)
console.log()
console.log(path.basename(__dirname))
console.log(path.basename(__filename))
console.log()
console.log(path.parse(__dirname))
console.log(path.parse(__filename))
console.log()
console.log(path.extname(__dirname))
console.log(path.extname(__filename))
console.log()
console.log(path.format(path.parse(__filename)))
console.log()
console.log(path.isAbsolute(__dirname))
console.log(path.isAbsolute(__filename))
console.log(path.isAbsolute('./13-03-2026/path.js'))
